version: '3.8'

services:
  backend:
    build: ./
    env_file:
      - .env
    ports:
      - 5050:5050
    volumes:
      - ./:/app
      - /app/node_modules
      - logs:/app/logs

    working_dir: /app

    command: npm run dev

    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  logs:
